version: '3.8'
services:
  web:
    build: .
    container_name: lamp_web_sec
    ports:
      - "8090:80"       # map host port 8090 to container port 80
    volumes:
      - ./:/var/www/html  # attach current code directory as volume inside container
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: lamp_db_sec
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
