version: '3.8'

services:
  web:
    build: ./std_mgmt_app
    container_name: lamp_web
    ports:
      - "8090:80"      # CI uses 8090 so it won’t collide with 80 from part 1
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: student_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
